//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBMS_RMS_PROJECT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Train
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Train()
        {
            this.tbl_Passenger = new HashSet<tbl_Passenger>();
            this.tbl_Station = new HashSet<tbl_Station>();
        }
    
        public int Train_No { get; set; }
        public string T_Name { get; set; }
        public string T_Desination { get; set; }
        public string T_DepartureTime { get; set; }
        public string T_ArrivalTime { get; set; }
        public Nullable<int> T_seats_Available { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Passenger> tbl_Passenger { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Station> tbl_Station { get; set; }
    }
}
