//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBMS_RMS_PROJECT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_User()
        {
            this.tbl_Station = new HashSet<tbl_Station>();
            this.tbl_Ticket = new HashSet<tbl_Ticket>();
        }
    
        public int U_Id { get; set; }
        public string U_Fname { get; set; }
        public string U_Lname { get; set; }
        public Nullable<int> U_Mobile_No { get; set; }
        public string U_Email { get; set; }
        public string U_Age { get; set; }
        public string U_Gender { get; set; }
        public string U_Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Station> tbl_Station { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Ticket> tbl_Ticket { get; set; }
    }
}
