//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBMS_RMS_PROJECT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Ticket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Ticket()
        {
            this.tbl_Ticket_Category = new HashSet<tbl_Ticket_Category>();
        }
    
        public int t_ID { get; set; }
        public Nullable<int> t_BookedUser { get; set; }
        public Nullable<int> t_PassengrNo { get; set; }
        public Nullable<int> t_Payment { get; set; }
        public Nullable<int> P_ID { get; set; }
        public Nullable<int> U_Id { get; set; }
        public Nullable<int> S_No { get; set; }
    
        public virtual tbl_Passenger tbl_Passenger { get; set; }
        public virtual tbl_Station tbl_Station { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Ticket_Category> tbl_Ticket_Category { get; set; }
        public virtual tbl_User tbl_User { get; set; }
    }
}
