//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBMS_RMS_PROJECT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Ticket_Category
    {
        public int tc_id { get; set; }
        public Nullable<int> tc_Gernal { get; set; }
        public Nullable<int> tc_Businsman { get; set; }
        public Nullable<int> tc_parliment { get; set; }
        public Nullable<int> tc_Economy { get; set; }
        public Nullable<int> t_ID { get; set; }
    
        public virtual tbl_Ticket tbl_Ticket { get; set; }
    }
}
