//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBMS_RMS_PROJECT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Passenger_Detial
    {
        public int pd_id { get; set; }
        public string pd_name { get; set; }
        public Nullable<int> pd_Age { get; set; }
        public string pd_Email { get; set; }
        public Nullable<int> P_ID { get; set; }
    
        public virtual tbl_Passenger tbl_Passenger { get; set; }
    }
}
