//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBMS_RMS_PROJECT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Station
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Station()
        {
            this.tbl_Ticket = new HashSet<tbl_Ticket>();
        }
    
        public int S_No { get; set; }
        public string S_Name { get; set; }
        public string S_ArrivalTime { get; set; }
        public Nullable<int> U_Id { get; set; }
        public Nullable<int> Train_No { get; set; }
    
        public virtual tbl_Train tbl_Train { get; set; }
        public virtual tbl_User tbl_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Ticket> tbl_Ticket { get; set; }
    }
}
